//! TERMINOLOGI ANDROID

//! 1. APA ITU ANDROID
/*
 * ANDROID ADALAH SEBUAH SISTEM OPERASI BERBASI LINUX YANG DIRANCANG UNTUK PERANGKAT LAYAR SENTUH SEPERTI HANDPHONE DAN TABLET, TABLET, SMARTWATCH, SMAR TV DAN BAHKAN DASHBOARD MOBIL
 */
//TODO: ANDROID DI KEMBANGKAN OLEH ANDROID INC YG DIDIRIKAN OLEH ANDY RUBIN DAN DI BELI ATAU DI AKUSISI OLEH GOOGLE PADA TAHUN 2005 DAN DI RILIS RESMI PADA TAHUN 2007 DAN DI JUAL KE PUBLIK PADA TAHUN 2008

//TODO: BAHASA PEMROGRAMAN YANG DIGUNAKAN UNTUK MEMBUAT APLIKASI ANDROID ADALAH JAVA DAN KOTLIN UNTUK BAGIAN LOGIC DAN XML UNTUK BAGIAN UI SEPERTI COMPONENT LAYOUT,
// TODO: TPI BAHASA RESMI YG DISARANKAN GOOGLE YANG DIGUNAKAN UNTUK MEMBUAT APLIKASI ANDROID ADALAH KOTLIN DAN XML

//TODO: JADI ANALOGINYA XML ITU KAYA HTML DI WEB DAN JAVA DAN KOTLIN ITU KAYA JAVASCRIPT DI WEB

//TODO: NOTES: ANDROID STUDIO ADALAH SEBUAH SOFTWARE IDE (INTEGRATED DEVELOPMENT ENVIRONMENT) YG DIGUNKAN UNTUK MEMBANTU KITA MEMBUAT APLIKASI ANDROID

//! 2. APA ITU ANDROID SDK
/*
 * ANDROID SDK ADALAH SEBUAH TOOLS ATAU PKG YG DIGUNAKAN UNTUK MEMBANTU KITA MEMBUAT APLIKASI ANDROID
    TODO: CONTOHNYA BUAT COMPILE APLIKASI KITA DAN MENJALANKANNYA DI DEVICE

    todo:note api level adalah fungsi" atau fitur yg disediakan dari versi android tertentu untuk mengembangkan aplikasi android



 */
