//! TERMINOLOGI ANDROID

//! 1. APA ITU ANDROID
/*
 * ANDROID ADALAH SEBUAH SISTEM OPERASI BERBASI LINUX YANG DIRANCANG UNTUK PERANGKAT LAYAR SENTUH SEPERTI HANDPHONE DAN TABLET, SMARTWATCH, SMAR TV DAN BAHKAN DASHBOARD MOBIL
 */
//TODO: ANDROID DI KEMBANGKAN OLEH ANDROID INC YG DIDIRIKAN OLEH ANDY RUBIN tahum 2003 DAN DI BELI ATAU DI AKUSISI OLEH GOOGLE PADA TAHUN 2005 DAN DI RILIS RESMI PADA TAHUN 2007 DAN DI JUAL KE PUBLIK PADA TAHUN 2008

//TODO: BAHASA PEMROGRAMAN YANG DIGUNAKAN UNTUK MEMBUAT APLIKASI ANDROID ADALAH JAVA DAN KOTLIN UNTUK BAGIAN LOGIC DAN XML UNTUK BAGIAN UI SEPERTI COMPONENT LAYOUT,
// TODO: TPI BAHASA RESMI YG DISARANKaAN GOOGLE YANG DIGUNAKAN UNTUK MEMBUAT APLIKASI ANDROID ADALAH KOTLIN DAN XML

//TODO: JADI ANALOGINYA XML ITU KAYA HTML DI WEB DAN JAVA DAN KOTLIN ITU KAYA JAVASCRIPT DI WEB

//TODO: NOTES: ANDROID STUDIO ADALAH SEBUAH SOFTWARE IDE (INTEGRATED DEVELOPMENT ENVIRONMENT) YG DIGUNKAN UNTUK MEMBANTU KITA MEMBUAT APLIKASI ANDROID

//! 2. APA ITU ANDROID SDK
/*
 * ANDROID SDK ADALAH SEBUAH TOOLS ATAU PKG YG DIGUNAKAN UNTUK MEMBANTU KITA MENGEMBANGKAN APLIKASI ANDROID
    TODO: CONTOHNYA BUAT COMPILE APLIKASI KITA DAN MENJALANKANNYA DI DEVICE

    todo:note API LEVEL adalah fungsi" atau fitur yg disediakan ATAU ADA di versi android tertentu untuk mengembangkan aplikasi android

    todo: minimum sdk adalah sebuah cara untuk menentukan minimal versi android yg bisa menginstal aplikasi kita
    todo: target sdk adalah sebuah cara untuk menentukan target  versi android yg disarankan untuk menggunakan aplikasi kita 
    todo: maksimal sdk adalah sebuah cara untuk menentukan maksimial versi android yg bisa menginstal aplikasi kita 

    ! ANDROID VIRTUAL DEVICE (ADB)
    * SEBUAH VIRTUAL DEVICE YG KITA GUNAKAN UNTUK TEST ATAU MENJALANKAN APLIKASI ANDROID KITA 


   TODO: ALUR BUILD
   TODO: 1. COMPILER AKAN MELAKUKAN KOMPULASI ATAU MENGUMPULKAN SEMUA INFORMASI DARI CODE KITA DAN MEGNUBAHNYA MENJADI FILE DEX (DALVIX EXECUTABLE)
   TODO: 2. APK MANAGER AKAN MENANDAI FILE APAKAH INI VERSI DEBUG ATAU RELEASE SEBELUM AKHIRNYA DI JADIKAN FORMAT .APK ATAU .AAB
 */

//! 3. ANDROID BUILD SYSTEM
/*
   ? ANDROID BUILD SYSTEM SEBUAH PROSE COMPILE KODE PROGRAM DAN RESOURCE & NGEBUILD MENJADI APLIKASI ANDROID


   ! PROSESS BUILD
      /
         * 1. COMPILER AKAN MELAKUKAN KOMPULASI ATAU MENGUMPULKAN CODE,DEPEDENCIES (LIBRARY ATAU PKG) DAN RESOURCE KITA MENJADI DEX (Dalvix Executable) file

         * 2. APK MANAGER AKAN MENANDAKAN FILE HASIL COMPILE APAKAH FILE ITU VERSI DEBUG ATAU RELEASE, DAN AKHIRNYA AKAN DI JADIKAN APLIKASI FILE DENGAN FORMAT .APK (ANDROID APLICATION PACKAGE) ATAU .ABB

      /
*/
